import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { RouterOutputs, api } from "~/utils/api";

// type Buildings = RouterOutputs["buildings"]["getAll"];

export default function Home() {
  const user = useUser();
  const { data: buildings } = api.buildings.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
          <div>
            {buildings?.map((building) => (
              <div key={building.id}>{building.name}</div>
            ))}
          </div>
          <div className="flex flex-col items-center gap-2">            
            {!!user ? <SignInButton /> : <SignOutButton />}
          </div>        
      </main>
    </>
  );
}
